<?php
declare(strict_types=1);

use Magento\Framework\Data\Tree\Node;
use Magento\Theme\Block\Html\Topmenu;

function getDataFromNode(Node $node) {
    $data = $node->getData();
    $data['children'] = [];
    foreach($node->getChildren() as $child) {
        $data['children'][] = getDataFromNode($child);
    }

    return $data;
}

/** @var $block Topmenu */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php
/** @var Node $menuTree */
$menuData = getDataFromNode($block->getMenu());
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"reactMenu":{"data": <?php echo json_encode($menuData) ?>}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>

<script>
    require([], function() {

    });
</script>


